services:
  task-manager-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: nodejs
    container_name: task-manager-api
    ports:
      - "3333:3333"
    depends_on:
      - task-manager-db

  task-manager-db:
    image: "bitnami/postgresql"
    container_name: task-manager-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task-manager-db
    volumes:
      - task-manager-db:/var/lib/postgresql/data

volumes:
  task-manager-db: